version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/usr/src/app/pages
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app/api
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
