version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/usr/src/app/pages
      - ./states:/usr/src/app/states
      - ./ui:/usr/src/app/ui
      - ./libs:/usr/src/app/libs
    command: ["npm", "run", "dev"]
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app/api
    command: ["npm", "run", "api:dev"]
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
      - web


