version: '3.9'
services:
  web:
    image: minamorl/tenet-web
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:462920645891:secret:dockerhubAccessToken-pPxdcS"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  # api:
    # build:
      # context: ./
      # dockerfile: ./api/Dockerfile
    # ports:
      # - "4000:4000"
